name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

  DOCKER_BUILDKIT: 1
  DOCKER_TAG_VERSION: latest

# SEE: percebus/github-actions-npm/.github/workflows/npm_test.yml@main
# "Invalid workflow file: .github/workflows/always.yml#L70
# The workflow is requesting 'actions: read, checks: write, pull-requests: write',
# but is only allowed 'actions: none, checks: none, pull-requests: none'.""
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  npm_test_projects:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        project:
          - express-app
          - rest-app

    env:
      WORKSPACE: ./node/${{ matrix.project }}
    name: npm test ${{ matrix.project }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main

      - name: ls
        run: ls -la ${{ env.WORKSPACE }}
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main
        with:
          working-directory: ${{ env.WORKSPACE }}

      - name: npm test
        working-directory: ${{ env.WORKSPACE }}
        run: npm test

  yarn_test_projects:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ./node/package-c
      YARN_CLI_OPTS: --cwd ./node/package-c
    strategy:
      max-parallel: 6
      matrix:
        project:
          - package-c

    name: yarn test ${{ matrix.project }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main

      - name: ls
        run: ls -la ${{ env.WORKSPACE }}

      - name: setup
        run: yarn ${{ env.YARN_CLI_OPTS }} run setup:ci
      - name: yarn install
        run: yarn ${{ env.YARN_CLI_OPTS }} run clean-install

      # TODO? or XXX? Not generating node_modules
      # - name: ls node_modules
      #   run: ls -la ${{ env.WORKSPACE }}/node_modules

      - name: yarn test
        run: yarn ${{ env.YARN_CLI_OPTS }} test

  npm_test:
    name: npm test
    runs-on: ubuntu-latest
    needs:
      - npm_test_projects
      - yarn_test_projects
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm test
        run: npm test

  yarn_test:
    name: yarn test
    runs-on: ubuntu-latest
    needs:
      - npm_test_projects
      - yarn_test_projects
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main

      - name: setup
        run: yarn run setup:ci
      - name: yarn install
        run: yarn run yarn:ci
      - name: ls node_modules
        run: ls -la ./node_modules

      - name: yarn test
        run: yarn test

  docker_compose:
    name: docker compose
    needs: npm_test
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - name: docker compose build
        run: docker compose build

  docker_build_matrix:
    name: docker build --target
    if: github.ref == 'refs/heads/main'
    needs: docker_compose
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        DOCKER_TARGET:
          - root
          #
          # These are tested by docker compose
          - express-app
          - rest-app
          # TODO add each package

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - name: "docker build: ${{ matrix.DOCKER_TARGET }}"
        run: |
          docker build . \
            --target ${{ matrix.DOCKER_TARGET }} \
            --tag ${{ env.REPOSITORY_NAME }}.${{ matrix.DOCKER_TARGET }}:${{ env.DOCKER_TAG_VERSION }}
