name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  IMAGE_TAG_SUFFIX: latest

  DOCKER_BUILDKIT: 1

# SEE:
# - percebus/github-actions-npm/.github/workflows/npm_test.yml@main
# - percebus/github-actions-docker/.github/actions/docker_build_target.yml@main
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  npm_test_projects:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        project:
          - express-app
          - rest-app
    name: "npm test: ${{ matrix.project }}"

    # FIXME
    # uses: percebus/github-actions-npm/.github/workflows/npm_test.yml@main
    # with:
    #   working-directory: ./node/${{ matrix.project }}
    #   # Not all projects have `jest-junit`
    #   reporter: none
    uses: percebus/github-actions-npm/.github/workflows/npm_run_script.yml@main
    with:
      working-directory: ./node/${{ matrix.project }}
      script: test

  #
  # yarn test matrix
  yarn_test_projects:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        project:
          - package-c
    name: "yarn test: ${{ matrix.project }}"
    uses: percebus/github-actions-yarn/.github/workflows/yarn_run_script.yml@main
    with:
      working-directory: ./node/${{ matrix.project }}
      script: test

  #
  # npm test
  npm_test:
    name: npm test
    needs:
      - npm_test_projects
      - yarn_test_projects
    uses: percebus/github-actions-npm/.github/workflows/npm_test.yml@main
    with:
      reporter: jest-junit
      files_pattern: ./node/*/junit.xml

  #
  # yarn test
  yarn_test:
    name: yarn test
    needs:
      - npm_test_projects
      - yarn_test_projects
    uses: percebus/github-actions-yarn/.github/workflows/yarn_run_script.yml@main
    with:
      script: test

  #
  # docker compose
  docker_compose:
    name: docker compose
    needs: npm_test
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - name: docker compose build
        run: docker compose build

  #
  # docker build
  docker_build_matrix:
    name: docker build --target
    # if: github.ref == 'refs/heads/main' # FIXME
    needs: docker_compose
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        target:
          - root
          #
          # These are tested by docker compose
          - express-app
          - rest-app
          # TODO add each package

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: percebus/github-actions-docker/.github/actions/docker_build_target@main
        with:
          target: ${{ matrix.target }}
          image_tag_suffix: ${{ env.IMAGE_TAG_SUFFIX }}
