name: Dependencies Review & Audit

on:
  # "This run was triggered by the "push" event, which is unsupported.
  #  Please ensure you are using the "pull_request" event for this workflow."
  pull_request:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

jobs:
  dependency-review:
    uses: percebus/github-actions-common/.github/workflows/dependency-review.yml@main

  audit:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        package_manager:
          - npm
          - yarn
    name: audit w/ ${{ matrix.package_manager }}
    uses: percebus/github-actions-${{ matrix.package_manager }}/.github/workflows/${{ matrix.package_manager }}_audit.yml@main
