name: Dependencies Review & Audit

on:
  # "This run was triggered by the "push" event, which is unsupported.
  #  Please ensure you are using the "pull_request" event for this workflow."
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    uses: percebus/github-actions-npm/.github/workflows/dependency-review.yml@main
